### ISSUE TITLE
iGenomes path is not correct

### ISSUE THREAD

**Issue by adomingues** [nf-core/clipseq#29] opened 2021-03-11 09:56 UTC
Hi all,

First of all thank you for developing the pipeline. I am running into what I think is bug but you might tell me better what is going on. I think it is an issue with the path to the AWS genomes.

## Check Documentation

I have checked the following places for your error:

- [ X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ X] [nf-core/clipseq pipeline documentation](https://nf-co.re/nf-core/clipseq/usage)

## Description of the bug

 When I ran the test pipeline everyting works fine (log at the bottom), however when I do a proper run the genome is not found: 

```bash
adomingues@ad-genome:~/genomics/projects/RBM20_clip$ nextflow run nf-core/clipseq --input "results/design.txt" --genome 'GRCh38' -profile "singularity" --smrna_org "human" --peakcaller all -r "dev"
N E X T F L O W  ~  version 20.10.0
Launching `nf-core/clipseq` [gloomy_caravaggio] - revision: a3c52c22d5 [dev]
s3:/ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Annotation/Genes/genes.gtf (No such file or directory)

 -- Check script '/home/adomingues/.nextflow/assets/nf-core/clipseq/main.nf' at line: 1465 or see '.nextflow.log' file for more details
```

It seems to me that the issue is that the path is malformed. The error message states `s3:/ngi-igenomes/` when, and judging from the nf-core docs, it should have been `s3://ngi-igenomes/`.

I also checked the log at the line referenced, but there is nothing I can deduce from there at what the error is:

```bash
adomingues@ad-genome:~/genomics/projects/RBM20_clip$ sed -n 1464,1470p /home/adomingues/.nextflow/assets/nf-core/clipseq/main.nf

  boolean gencode = false
  f.withReader { r ->
    while( count<n && ( !gene && ( !ensembl || !gencode ) ) ) {
        line = r.readLine();
        count = count + 1;
        if (!gene) {
            if (line =~ /\bgene\b/) {
```

I have also tried other genome versions, GRCh37 and hg38, but the error persists. Any help would be appreciated.

Cheers.

## Log files

Have you provided the following extra information/files:

- [ X The command used to run the pipeline
- [ X] The `.nextflow.log` file 

## System

- Hardware: HPC, VM
- Executor: local
- OS:Ubuntu Linux
- Version: 20.04

## Nextflow Installation

- Version: 20.10.0.5430

## Container engine

- Engine: Singularity
- version: 2.6.1-dist
- Image tag: nfcore/clipseq:dev

**Comment by amchakra** [comment] 2021-03-11 11:37
Thanks for highlighting! This is a little strange - `igenomes_base` is correct in `nextflow.config` with `s3://`. The problem is occurring within the function that checks to see if the GTF is compatible with iCount - @charlotte-west is updating this at the moment to reconfigure it into a process and I wonder if that might fix the issue.

**Comment by adomingues** [comment] 2021-03-11 13:14
Thanks for the quick reply @amchakra. I also thought it was a little strange because when I searched the source code it seemed like everything was properly set-up. By the looks of it, and very naively, it seems like a case of an escape character gone rogue. I look forward for the fix. 

Since this issue seems to specif for a iCount-related function, I decided to test using only a piranha which is enough for now (seems to be the only peak called dealing with PAR-clip), and this time there is a different error:

```bash
nextflow run nf-core/clipseq --input "/home/adomingues/genomics/projects/RBM20_clip/resu
lts/design.txt" --genome 'hg38' -profile "singularity" --smrna_org "human" --peakcaller "piranha" -r "dev"   
N E X T F L O W  ~  version 20.10.0                                                                                                                          Launching `nf-core/clipseq` [peaceful_feynman] - revision: a3c52c22d5 [dev]                                                                                  
----------------------------------------------------                          
                                        ,--./,-.                              
        ___     __   __   __   ___     /,-._.--~'                                                                                                            
  |\ | |__  __ /  ` /  \ |__) |__         }  {                                                                                                               
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,                             
                                        `._,._,'                                                                                                             
  nf-core/clipseq v1.0.0dev                                                                                                                                  
----------------------------------------------------                                                                                                         
Pipeline Release  : dev                
Run Name          : peaceful_feynman
Input             : /home/adomingues/genomics/projects/RBM20_clip/results/design.txt
Fasta ref         : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa
GTF ref           : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf
STAR index        : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Sequence/STARIndex/
SmallRNA organism ref: human
SmalRNA ref       : [/home/adomingues/.nextflow/assets/nf-core/clipseq/assets/small_rna/Homo_sapiens/Homo_sapiens.final.smallRNA.fa.gz]
Deduplicate       : true
UMI separator     : :
Peak caller       : piranha
Bin size          : 3
Cluster distance  : 3
Max Resources     : 16 GB memory, 8 cpus, 10d time per job
Container         : singularity - nfcore/clipseq:dev
Output dir        : ./results
Launch dir        : /mnt/projects/genomics/projects/RBM20_clip
Working dir       : /mnt/projects/genomics/projects/RBM20_clip/work
Script dir        : /home/adomingues/.nextflow/assets/nf-core/clipseq
User              : adomingues
Config Profile    : singularity
Config Files      : /home/adomingues/.nextflow/assets/nf-core/clipseq/nextflow.config
----------------------------------------------------
executor >  local (3)
executor >  local (3)
executor >  local (3)
[57/8239a4] process > get_software_versions                                     [  0%] 0 of 1
[c9/f93b05] process > generate_premap_index (Homo_sapiens.final.smallRNA.fa.gz) [100%] 1 of 1, failed: 1 ✘
[-        ] process > generate_fai                                              -
[-        ] process > fastqc                                                    [  0%] 0 of 3
[ef/ffe6d5] process > cutadapt (rbm20_4su)                                      [ 33%] 1 of 3, failed: 1
[-        ] process > premap                                                    -
[-        ] process > align                                                     -
[-        ] process > preseq                                                    -
[-        ] process > dedup                                                     -
[-        ] process > rseqc                                                     -
[-        ] process > get_crosslinks                                            -
[-        ] process > piranha_peak_call                                         -
[-        ] process > piranha_motif_dreme                                       -
[-        ] process > clipqc                                                    [  0%] 0 of 1
[-        ] process > multiqc                                                   -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'generate_premap_index (Homo_sapiens.final.smallRNA.fa.gz)'

Caused by:
  Process `generate_premap_index (Homo_sapiens.final.smallRNA.fa.gz)` terminated with an error exit status (127)

Command executed:

  bowtie2-build --threads 2 Homo_sapiens.final.smallRNA.fa.gz Homo_sapiens

Command exit status:
  127

Command output:
  (empty)

Command error:
  WARNING: Non existent 'bind path' source: '/beegfs/work/'
  WARNING: Non existent 'bind path' source: '/scratch'
  WARNING: Non existent 'bind path' source: '/gpfs'
  WARNING: Not mounting requested bind point (already mounted in container): /mnt/projects/genomics/projects/RBM20_clip/work/c9/f93b05ebba79ba7b886ff56bc002e9                                      
  .command.sh: line 2: bowtie2-build: command not found

Work dir:
  /mnt/projects/genomics/projects/RBM20_clip/work/c9/f93b05ebba79ba7b886ff56bc002e9

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Genome reference fasta not found: s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa
Genome reference gtf not found: s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf
```

I searched only for the cause, and all answers seem to point to an issue with singularity mount points / paths. I changed the singularity config file as suggested [here](https://nf-co.re/usage/troubleshooting#cannot-find-input-files-when-using-singularity), but the error persist. It ti is relevant, I am running the pipeline inside a VM (linux ubuntu). Do you have any suggestions on how to fix this? Please let me know if I should create separate issue.

**Comment by amchakra** [comment] 2021-03-25 11:24
This is now fixed in the `pr-review` branch and will be incorporated into the release soon. Thanks for checking the fix worked @adomingues!

**Closed by amchakra** 2021-03-25 11:24 UTC
Labels: bug
